/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppContainer: typeof import('./src/components/AppContainer.vue')['default']
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    AppTimeline: typeof import('./src/components/AppTimeline.vue')['default']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PostTimeline: typeof import('./src/components/PostTimeline.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Template: typeof import('./src/components/template.vue')['default']
    UserBar: typeof import('./src/components/UserBar.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
